"""users table

Revision ID: 81efa4e5629e
Revises: 20fce3103d91
Create Date: 2026-08-28 13:55:27.091232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81efa4e5629e'
down_revision = '20fce3103d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
